- name: Print message
  debug:
    msg: "foo is {{ foo }}"

- name: another way
  debug:
    var: foo

- name: yet another way
  shell: "foo={{ foo }}; echo $foo"
  register: foo1

- debug:
    var: foo1.stdout
